#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE_DIR="${SCRIPT_DIR}/proxy_profiles"
CURRENT_ENV_FILE="${PROFILE_DIR}/current.env"
DEFAULT_NO_PROXY="localhost,127.0.0.1,::1"

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/proxy_common.sh"

usage() {
    cat <<'EOF'
Usage:
  ./switch_proxy_mode.sh corporate
  ./switch_proxy_mode.sh wifi
  ./switch_proxy_mode.sh status

Profiles:
  corporate  Use the corporate LAN proxy settings saved in proxy_profiles/corporate.env
  wifi       Disable proxy for direct internet access via Wi-Fi/router
  status     Show the currently saved profile and GNOME proxy status
EOF
}

trim_gsettings_string() {
    local value="${1:-}"
    value="${value#\'}"
    value="${value%\'}"
    printf '%s' "${value}"
}

emit_export_if_set() {
    local name="$1"
    local value="${!name:-}"
    if [[ -n "${value}" ]]; then
        printf 'export %s=%q\n' "${name}" "${value}"
    fi
}

apply_gnome_proxy() {
    if ! command -v gsettings >/dev/null 2>&1; then
        echo "[INFO] gsettings がないため OS プロキシ設定の切替はスキップしました。"
        return
    fi

    local mode="${PROXY_MODE:-none}"
    local ignore_hosts_literal="${GNOME_IGNORE_HOSTS_LITERAL:-['localhost', '127.0.0.0/8', '::1']}"

    gsettings set org.gnome.system.proxy ignore-hosts "${ignore_hosts_literal}" >/dev/null 2>&1 || true

    if [[ "${mode}" == "manual" ]]; then
        gsettings set org.gnome.system.proxy.http host "${GNOME_HTTP_HOST:-127.0.0.1}" >/dev/null 2>&1 || true
        gsettings set org.gnome.system.proxy.http port "${GNOME_HTTP_PORT:-3128}" >/dev/null 2>&1 || true
        gsettings set org.gnome.system.proxy.https host "${GNOME_HTTPS_HOST:-${GNOME_HTTP_HOST:-127.0.0.1}}" >/dev/null 2>&1 || true
        gsettings set org.gnome.system.proxy.https port "${GNOME_HTTPS_PORT:-${GNOME_HTTP_PORT:-3128}}" >/dev/null 2>&1 || true

        if [[ -n "${GNOME_SOCKS_HOST:-}" ]]; then
            gsettings set org.gnome.system.proxy.socks host "${GNOME_SOCKS_HOST}" >/dev/null 2>&1 || true
        fi
        if [[ -n "${GNOME_SOCKS_PORT:-}" ]]; then
            gsettings set org.gnome.system.proxy.socks port "${GNOME_SOCKS_PORT}" >/dev/null 2>&1 || true
        fi

        gsettings set org.gnome.system.proxy mode 'manual' >/dev/null 2>&1 || true
    else
        gsettings set org.gnome.system.proxy mode 'none' >/dev/null 2>&1 || true
    fi
}

write_current_env() {
    mkdir -p "${PROFILE_DIR}"

    {
        echo "# Generated by switch_proxy_mode.sh"
        echo "export PROXY_PROFILE=${PROFILE_NAME@Q}"
        echo "unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY all_proxy NO_PROXY no_proxy"
        emit_export_if_set HTTP_PROXY
        emit_export_if_set HTTPS_PROXY
        emit_export_if_set ALL_PROXY
        printf 'export NO_PROXY=%q\n' "${NO_PROXY:-${DEFAULT_NO_PROXY}}"
        if [[ -n "${HTTP_PROXY:-}" ]]; then
            printf 'export http_proxy=%q\n' "${HTTP_PROXY}"
        fi
        if [[ -n "${HTTPS_PROXY:-}" ]]; then
            printf 'export https_proxy=%q\n' "${HTTPS_PROXY}"
        fi
        if [[ -n "${ALL_PROXY:-}" ]]; then
            printf 'export all_proxy=%q\n' "${ALL_PROXY}"
        fi
        printf 'export no_proxy=%q\n' "${NO_PROXY:-${DEFAULT_NO_PROXY}}"
    } > "${CURRENT_ENV_FILE}"
}

show_status() {
    local saved_profile="unset"
    if [[ -f "${CURRENT_ENV_FILE}" ]]; then
        saved_profile="$(sed -n "s/^export PROXY_PROFILE=//p" "${CURRENT_ENV_FILE}" | head -n 1 | tr -d "'\"")"
        [[ -z "${saved_profile}" ]] && saved_profile="custom"
    fi

    echo "Saved profile: ${saved_profile}"

    if command -v gsettings >/dev/null 2>&1; then
        local mode http_host http_port https_host https_port
        mode="$(gsettings get org.gnome.system.proxy mode 2>/dev/null || true)"
        http_host="$(trim_gsettings_string "$(gsettings get org.gnome.system.proxy.http host 2>/dev/null || true)")"
        http_port="$(gsettings get org.gnome.system.proxy.http port 2>/dev/null || true)"
        https_host="$(trim_gsettings_string "$(gsettings get org.gnome.system.proxy.https host 2>/dev/null || true)")"
        https_port="$(gsettings get org.gnome.system.proxy.https port 2>/dev/null || true)"

        echo "GNOME proxy mode: ${mode:-unknown}"
        echo "GNOME http proxy: ${http_host:-unset}:${http_port:-unset}"
        echo "GNOME https proxy: ${https_host:-unset}:${https_port:-unset}"
    fi

    clear_proxy_env
    if [[ -f "${CURRENT_ENV_FILE}" ]]; then
        # shellcheck disable=SC1090
        source "${CURRENT_ENV_FILE}"
    fi

    echo "Project HTTP_PROXY: ${HTTP_PROXY:-unset}"
    echo "Project HTTPS_PROXY: ${HTTPS_PROXY:-unset}"
    echo "Project NO_PROXY: ${NO_PROXY:-unset}"
}

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

PROFILE_NAME="$1"

case "${PROFILE_NAME}" in
    status)
        show_status
        exit 0
        ;;
    corporate|wifi)
        ;;
    *)
        usage
        exit 1
        ;;
esac

PROFILE_FILE="${PROFILE_DIR}/${PROFILE_NAME}.env"

if [[ ! -f "${PROFILE_FILE}" ]]; then
    echo "Profile file not found: ${PROFILE_FILE}" >&2
    echo "Create it first, then run this script again." >&2
    exit 1
fi

clear_proxy_env
set -a
# shellcheck disable=SC1090
source "${PROFILE_FILE}"
set +a

: "${PROXY_MODE:=none}"
: "${NO_PROXY:=${DEFAULT_NO_PROXY}}"

write_current_env
apply_gnome_proxy

echo "Switched proxy profile to: ${PROFILE_NAME}"
echo "Saved state file: ${CURRENT_ENV_FILE}"
echo "HTTP_PROXY=${HTTP_PROXY:-unset}"
echo "HTTPS_PROXY=${HTTPS_PROXY:-unset}"
echo "NO_PROXY=${NO_PROXY:-unset}"
